export default [
  ['Arts & Entertainment', 'Industry', 'Innovation & Tech', 'Life',],
  [
    [
      'Art',
      'Beauty',
      'Culture',
      'Fiction',
      'Film',
      'Food',
      'Gaming',
      'Humor',
      'Music',
      'Nonfiction',
      'Sports',
    ],
    [
      'Business',
      'Design',
      'Freelancing',
      'Leadership',
      'Marketing',
      'Product Management',
      'Productivity',
      'Remote Work',
      'Startups',
      'Venture Capital',
    ],
    [
      'Accessibility',
      'Android Dev',
      'Artificial Intelligence',
      'Blockchain',
      'Cyroptocurrency',
      'Cybersecurity',
      'Data Science',
      'Gadgets',
      'iOS Dev',
      'Javascript',
      'Machine Learning',
      'Math',
      'Neuroscience',
      'Programming',
      'Science',
      'Space',
      'Technology',
      'UX',
      'Visual Design',
    ],
    [
      'Addiction',
      'Creativity',
      'Disability',
      'Family',
      'Fitness',
      'Health',
      'Lifestyle',
      'Mental Health',
      'Mindfulness',
      'Money',
      'Outdoors',
      'Parenting',
      'Pets',
      'Psychology',
      'Relationships',
      'Self',
      'Sexuality',
      'Spirituality',
      'Travel',
    ],
  ]
]